### PR TITLE
Fix typo in default bundle that resulted in incorrect output for the help command.

### LINKED ISSUE #204: The `help FOO` command returns the wrong help text
The `!help foo` command should return the help text for the `foo` command, but instead returns the text for `gort hidden`.

### PR DESCRIPTION
**Pull request by theothertomelliott**
Fixes #204

### CODE REVIEW

**Comment by theothertomelliott** [comment]
Seems a worthwhile quick fix to main. But let me know if you'd prefer this to live on develop.

**Review by clockworksoul — APPROVED** [review]
Thank you!

**Comment by theothertomelliott** [comment]
Yep, see above comment. But also open to putting on develop if preferred.

**Comment by theothertomelliott** [comment]
Closing since this should be on develop.

**Pull request closed without merging**
